[workspace]
members = [
  "brotli-encoder",
  "clients/rust-client-app",
  "clients/rust-test-read-file",
  "macroquad",
  "macroquad/guests/basic-shapes-example",
  "levo-server",
  "portal",
]
resolver = "2"
